apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
  labels:
    app: my-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-app
        # 【重要】这里先写个占位符，GitHub Actions 会自动替换它
        # 格式：你的ECR地址/仓库名:标签
        image: <IMAGE_URI> 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-python-app-service
spec:
  selector:
    app: my-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # 固定映射到 EC2 的 30080 端口，方便访问
  type: NodePort
